apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  labels:
    app: ophicelide-training
    name: ophicelide-training
  name: ophicelide-training
spec:
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    type: None
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: "node('maven') {\n\n  stage 'build & deploy in dev'\n  openshiftBuild(namespace:
        'development',\n                   buildConfig: 'ophicleide-training',\n                   showBuildLogs:
        'true',\n                   waitTime: '3000000')\t\t   \n\n  stage 'verify
        deploy in dev'\n  openshiftVerifyDeployment(namespace: 'development',\n\t\t\t\t
        \      depCfg: 'ophicleide',\n\t\t\t\t       replicaCount:'1',\n\t\t\t\t       verifyReplicaCount:
        'true',\n\t\t\t\t       waitTime: '300000')\n  \n  stage 'deploy in test'\n
        \ openshiftTag(namespace: 'development',\n  \t\t\tsourceStream: 'ophicleide-training',\n\t\t\t
        \ sourceTag: 'latest',\n\t\t\t  destinationStream: 'ophicleide-training',\n\t\t\t
        \ destinationTag: 'promoteQA')\n  \n  openshiftTag(namespace: 'development',\n
        \ \t\t\t  sourceStream: 'ophicleide-web',\n\t\t\t  sourceTag: 'latest',\n\t\t\t
        \ destinationStream: 'ophicleide-web',\n\t\t\t  destinationTag: 'promoteQA')\n
        \ \n  openshiftDeploy(namespace: 'testing',\n  \t\t\t     deploymentConfig:
        'ophicleide',\n\t\t\t       waitTime: '300000')\n\n  openshiftScale(namespace:
        'testing',\n  \t\t\t     deploymentConfig: 'ophicleide',\n\t\t\t     waitTime:
        '300000',\n\t\t\t     replicaCount: '1')\n  \n  stage 'verify deploy in test'\n
        \ openshiftVerifyDeployment(namespace: 'testing',\n\t\t\t\t       depCfg:
        'ophicleide',\n\t\t\t\t       replicaCount:'1',\n\t\t\t\t       verifyReplicaCount:
        'true',\n\t\t\t\t       waitTime: '300000')\n  \n  stage 'Deploy to production'\n
        \ timeout(time: 2, unit: 'DAYS') {\n      input message: 'Approve to production?'\n
        \ }\n\n  openshiftTag(namespace: 'development',\n  \t\t\t  sourceStream: 'ophicleide-web',\n\t\t\t
        \ sourceTag: 'latest',\n\t\t\t  destinationStream: 'ophicleide-web',\n\t\t\t
        \ destinationTag: 'promotePRD')\n\n  openshiftTag(namespace: 'development',\n
        \ \t\t\t  sourceStream: 'ophicleide-training',\n\t\t\t  sourceTag: 'latest',\n\t\t\t
        \ destinationStream: 'ophicleide-training',\n\t\t\t  destinationTag: 'promotePRD')\n
        \ \n  openshiftDeploy(namespace: 'production',\n  \t\t\t     deploymentConfig:
        'ophicleide',\n\t\t\t     waitTime: '300000')\n  \n  openshiftScale(namespace:
        'production',\n  \t\t\t     deploymentConfig: 'ophicleide',\n\t\t\t     waitTime:
        '300000',\n\t\t\t     replicaCount: '1')\n  \n  stage 'verify deploy in production'\n
        \ openshiftVerifyDeployment(namespace: 'production',\n\t\t\t\t       depCfg:
        'ophicelide',\n\t\t\t\t       replicaCount:'1',\n\t\t\t\t       verifyReplicaCount:
        'true',\n\t\t\t\t       waitTime: '300000')\n}"
    type: JenkinsPipeline
  triggers:
  - github:
      secret: secret101
    type: GitHub
  - generic:
      secret: secret101
    type: Generic
status:
  lastVersion: 0